name: Decrypt features.md

on:
  push:
    branches:
      - master
jobs:
  decrypt:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3

      - name: Decrypt features.md
        run: |
          openssl version
          cat features.md
