name: Decrypt features.md

on:
  push:
    branches:
      - main

jobs:
  decrypt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decrypt features.md
        run: |
          openssl aes-256-cbc -d -salt -in features.md.enc -out features.md -pbkdf2 -pass pass:$FEATURES_FILE_PASSPHRASE
          cat features.md
